source("rankall.R")

head(rankall("heart attack", 20), 10)
# hospital state
# <NA>    AK
# D W MCMILLAN MEMORIAL HOSPITAL    AL
# ARKANSAS METHODIST MEDICAL CENTER    AR
# JOHN C LINCOLN DEER VALLEY HOSPITAL    AZ
# SHERMAN OAKS HOSPITAL    CA
# SKY RIDGE MEDICAL CENTER    CO
# MIDSTATE MEDICAL CENTER    CT
# <NA>    DC
# <NA>    DE
# SOUTH FLORIDA BAPTIST HOSPITAL    FL

tail(rankall("pneumonia", "worst"), 3)
# hospital state
# WI MAYO CLINIC HEALTH SYSTEM - NORTHLAND, INC    WI
# WV                     PLATEAU MEDICAL CENTER    WV
# WY           NORTH BIG HORN HOSPITAL DISTRICT    WY

tail(rankall("heart failure"), 10)
# hospital state
# WELLMONT HAWKINS COUNTY MEMORIAL HOSPITAL    TN
# FORT DUNCAN MEDICAL CENTER    TX
# SALT LAKE CITY HEALTHCARE - GEORGE E. WAHLEN VA MEDICAL CENTER    UT
# SENTARA POTOMAC HOSPITAL    VA
# GOV JUAN F LUIS HOSPITAL & MEDICAL CTR    VI
# SPRINGFIELD HOSPITAL    VT
# HARBORVIEW MEDICAL CENTER    WA
# AURORA ST LUKES MEDICAL CENTER    WI
# FAIRMONT GENERAL HOSPITAL    WV
# CHEYENNE VA MEDICAL CENTER    WY